[package]
name = "opa-compiler"
version = "0.1.0"
authors = ["Mike Yagley <myagley@gmail.com>"]
edition = "2018"

[dependencies]
opa-compiler-sys = { version = "0.1.0", path = "../opa-compiler-sys" }
